### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by Unmasked187** [oSumAtrIX/dinkleberg#2]
If the bot is not in the server which one u selected then u will get this error.

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Http(UnsuccessfulRequest(ErrorResponse { status_code: 403, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("discord.com")), port: None, path: "/api/v9/guilds/558736576830767134", query: Some("with_counts=true"), fragment: None }, error: DiscordJsonError { code: 50001, message: "Missing Access", errors: [] } }))', src\handler.rs:39:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Best Regards Frank

**Comment by oSumAtrIX** [comment]
Instead, this error should be handled and a message should be given to the user letting him know about the problem

**Comment by oSumAtrIX** [comment]
Fixed in commit aca2ffb2db8b034a819ec8eb3dd384985a4a699b
